Convert all dependencies to steps

diff --git a/atomics/T1110.001/4097bc00-5eeb-4d56-aaf9-287d60351d95.yaml b/atomics/T1110.001/4097bc00-5eeb-4d56-aaf9-287d60351d95.yaml
--- a/atomics/T1110.001/4097bc00-5eeb-4d56-aaf9-287d60351d95.yaml
+++ b/atomics/T1110.001/4097bc00-5eeb-4d56-aaf9-287d60351d95.yaml
@@ -17,6 +17,16 @@ requirements:
     platforms:
         - os: linux
 steps:
+    - name: |
+        Check if running on a Redhat based machine.
+      inline: |
+        if grep -iq "rhel\|fedora\|centos" /usr/lib/os-release; then echo "RedHat"; else echo "NOT RedHat"; {yum update && yum install -y openssl sudo curl
+        }; fi
+        if grep -Rq "pam_faillock" /etc/pam.d/*; then echo "pam_faillock configured"; exit 1; fi
+        if [ -x "$(command -v openssl)" ]; then echo "openssl is installed"; else echo "openssl is NOT installed"; exit 1; fi
+        if [ -x "$(command -v sudo)" ]; then echo "sudo is installed"; else echo "sudo is NOT installed"; exit 1; fi
+        if [ -x "$(command -v curl)" ]; then echo "curl is installed"; else echo "curl is NOT installed"; exit 1; fi
+      executor: bash
     - name: sudo-brute-force---redhat
       inline: |
         useradd -G wheel -s /bin/bash -p $(openssl passwd -1 password123) art
